version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    restart: always
    ports:
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./prisma:/app/prisma
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://altailands.ru
      - NEXT_PUBLIC_UPLOAD_PATH=/uploads
      - UPLOAD_PATH=/app/public/uploads
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./public/uploads:/app/public/uploads:ro
    depends_on:
      - nextjs
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 